apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banana

resources:
  - 01-deployment.yaml
  - 02-service.yaml
  - 03-tls-secret.yaml

commonLabels:
  app.kubernetes.io/name: banana-front
  app.kubernetes.io/component: banana-front
  app.kubernetes.io/part-of: banana