---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: banana
data:
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://172.16.16.8:5432/keycloak"
  KC_HTTP_ENABLED: "true"
  KC_PROXY: "edge"
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"
  KC_HOSTNAME: "oidc.bananaam.fr"
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "true"