---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secret
  namespace: banana
spec:
  refreshInterval: 20s
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: keycloak-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: id:29c4f549-94b6-49fa-9838-bf632c057ab6
        version: latest_enabled
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: id:e7f36ba0-48a8-4e90-a02d-b5ca5e663ca8
        version: latest_enabled
    - secretKey: KEYCLOAK_ADMIN
      remoteRef:
        key: id:93d6973b-dd5b-459b-a1f4-2dba208514bf
        version: latest_enabled
    - secretKey: KEYCLOAK_ADMIN_PASSWORD
      remoteRef:
        key: id:06e45c29-0695-4c1f-b078-ad229500c8e9
        version: latest_enabled