apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banana

resources:
  - 01-external-secret.yaml
  - 02-configmap.yaml
  - 08-keycloak-importer-operator.yaml
  - 04-service.yaml
  - 05-service-admin.yaml
  - 06-ingress.yaml
  - 07-network-policy.yaml
  - 08-keycloak-banana-realm.yaml

commonLabels:
  app.kubernetes.io/name: keycloak
  app.kubernetes.io/component: identity-management
  app.kubernetes.io/part-of: banana