---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin-secrets
  namespace: banana
spec:
  refreshInterval: 20s
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: keycloak-admin-secrets
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: id:93d6973b-dd5b-459b-a1f4-2dba208514bf
        version: latest_enabled
    - secretKey: password
      remoteRef:
        key: id:06e45c29-0695-4c1f-b078-ad229500c8e9
        version: latest_enabled