apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: banana
spec:
  instances: 1
  db:
    vendor: postgres
    host: 172.16.16.8
    port: 5432
    database: keycloak
    usernameSecret:
      name: keycloak-secrets
      key: POSTGRES_USER
    passwordSecret:
      name: keycloak-secrets
      key: POSTGRES_PASSWORD
  bootstrapAdmin:
    user:
      secret: keycloak-admin-secrets
  http:
    # Serve HTTP internally; TLS terminates at Ingress
    # httpEnabled defaults to true; keep tlsSecret unset to avoid internal HTTPS
    httpEnabled: true
    httpPort: 8180
#    httpsPort: 8443
  ingress:
    enabled: false
    # Ingress will be managed by with-operator/04-tls-ingress.yaml
  hostname:
    hostname: oidc.bananaam.fr
#    admin: oidc.bananaam.fr
    strict: true
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers

  readinessProbe:
    periodSeconds: 20
    failureThreshold: 5
  livenessProbe:
    periodSeconds: 20
    failureThreshold: 5
  startupProbe:
    periodSeconds: 20
    failureThreshold: 5