apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: banana
spec:
  instances: 1

  db:
    vendor: postgres
    host: 172.16.16.8
    port: 5432
    database: keycloak
    usernameSecret:
      name: keycloak-secrets
      key: POSTGRES_USER
    passwordSecret:
      name: keycloak-secrets
      key: POSTGRES_PASSWORD

  bootstrapAdmin:
    user:
      secret: keycloak-admin-secrets

  http:
    httpEnabled: true
    httpPort: 8180
  ingress:
    enabled: false
  hostname:
    hostname: https://oidc.bananaam.fr
    admin: https://oidc.bananaam.fr
    strict: false
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers

  resources:
    requests:
      cpu: 1200m
      memory: 896Mi
    limits:
      memory: 2Gi

  readinessProbe:
    periodSeconds: 20
    failureThreshold: 5
  livenessProbe:
    periodSeconds: 20
    failureThreshold: 5
  startupProbe:
    periodSeconds: 20
    failureThreshold: 5