apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banana

resources:
  - ../../../04-keycloak-operator/01-keycloak-operator.yaml
  - 01-database-secret.yaml
  - 02-keycloak-instance.yaml
  - 03-ingress.yaml
  - 04-realm-import.yaml

commonLabels:
  app.kubernetes.io/name: keycloak
  app.kubernetes.io/component: identity-management
  app.kubernetes.io/part-of: banana-platform
  app.kubernetes.io/managed-by: keycloak-operator